- name: AnsibleDocker Integration
  hosts: webserver
  become: true
  become_user: root
  tasks:
  - name: Install multiple packages on host
    package: name={{item}} state=present
    loop:
     - git
     - docker
     - tree
  - name: start docker services
    service: name=docker state=started
  - name: clone the git repo
    git:
     repo=https://github.com/Sonal0409/AnsibleDockerdemo.git
     dest=/tmp/myrepo
  - name: Build Docker image
    command: chdir=/tmp/myrepo docker build -t myansible .
  - name: Docker create container
    command: docker run -d -P myansible
